### ISSUE TITLE
Hỏi về Sendresult.

### ISSUE THREAD

**Issue by TechBK** [PiScale/god-eye#14]
@ntk148v chỗ này, biến `result` là `dict` kiên nhỉ?
https://github.com/PiScale/god-eye/blob/master/agent/sendresult.py#L29

**Comment by kinhvan017** [comment]
Tất nhiên rồi em.
=> https://github.com/influxdata/influxdb-python/blob/master/README.rst#examples

**Comment by ntk148v** [comment]
@TechBK chính xác. Form của result t đã bàn với Đại để Đại code theo r.

**Comment by TechBK** [comment]
hình như plugin của @daikk115 trả về một `list` các `dict`.
chỗ này mình có nên viết thế này để phù hợp với nhiều plugin không nhỉ?

```python
if isinstance(result, dict):
    send_như_bt
elseif isinstance(result,list):
    for res in result:
        sen_như_bt
```

**Comment by TechBK** [comment]
@ntk148v thế ông thêm phần form của result vào phần document nhé, kiểu như một phần nói về database. Để sau này anh em còn có cái để theo.
tạo một branch mới rồi pullrequest ý :D

**Comment by ntk148v** [comment]
t lam roi, ong check ho t xem ok chua.

**Comment by ntk148v** [comment]
@TechBK mỗi lần gửi thì chỉ gửi 1 result xong đẩy vào hàng đợi đúng k? và mỗi 1 result đấy có cấu trúc như t ghi ở trên, write_points(result) sẽ hiểu được nên không cần đoạn 'isinstance(result,list):'

**Comment by TechBK** [comment]
@ntk148v ok ông. nãy tưởng `result` là `dict` nên hỏi thế.
Hiểu ý ông rồi.
À reference doc vào đây luôn:
http://influxdb-python.readthedocs.io/en/latest/api-documentation.html#influxdb.InfluxDBClient.write_points
